# Generated by Django 5.2.16 on 2026-08-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
